dist: bionic
language: go
os: linux

go:
  - 1.15.x
  - tip

env:
  global:
    # REVIEWDOG_GITHUB_API_TOKEN
    secure: UDUOb+m3zOSfih/ai4WX5G9mIbNGDqh1ypKqPd0QiDwsVS7q1pSm9f0ZvboNTvGJFlREDLNznLD3TMlbqgNz3V73I/B+Ior8Ct8EVZdGlUlQoyIx78GNZpQ+xBkBZeIni9luoSODES9p2Snz5jASqintr+4jXKd6kTN5YmdBRYV9Ivs2GbCaMo/bvf85610mZtUaTm0aHLGdJ89VW2AZk4wxC4N0FUaEupzv/IoAIRZ75paX1ZrwniuReH26z5AvpPrCOOSYep482jo3KhpqCEoJuNOhHcLSfGpwVIKinBCJwnQrt9BvC3NJlJNkr21LwjUgUpjokKIrIifS3CiowjoklcvDk7QF9XqFO5SUw6OOKDJGQoZ7BLcOPVKJkRaa07sD/wftjZtUzw/7FjqPiXtgJVsHOX6vrH9Lnqv8t4ke3P12iJ9V5DfMd3Y0V+EtkJ/Z0rokLP5TmOwKkZKqKJSq7vUrBc4nHlhbfLdtuYwCS4Qo7+0EPiwYKaFFousYG0KLsqWtwqpgVKZLGcwRx2HTHMvxj/D52PkW7g7ZvX0fUdyTCyK/ZVsrwM+KG63Vc55jJGf7B+g3ZtxExGkoZxnjxYeo7yPxa4PCAilP8aOwqcvPk2CS71QvxkHdW7NSBnzOdtHaqj53Ju1P+cx+soxULGTl+JuSh7kbBUUiBos=

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

go_import_path: github.com/Percona-Lab/pmm-api-tests

before_cache:
  - go clean -testcache

cache:
  directories:
    - /home/travis/.cache/go-build
    - /home/travis/gopath/pkg

install: skip

before_script:
  - make init
  # static analyze
  - make ci-reviewdog

script:
  - make build

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: nvqu/KY2K0yNZv9WzqPP49RmkQzvscteV9AsECgIWXZziQhHkyn/yWCAeYPP6nnn76wzQkXfDLGQedGB3ceVebzWdrbcqG091x5FFIGz5YU4mSaWZHKfmS7CWbImDr+1vMJGDFfDBspYahx50PhtwURBA4WUw2C1wfiIMs79+JhxVbcYJqxDHLaaCddAf58TPtNGLibXLKkX0MLXsXfxp1ipheweT7n3jugzKNMgckxYzxrZwlq7ZZOA4IxuwrBkHBDaxrukWAgT+qB9Y6HEJRI6jDuDcaIBfpafhh+4kFyawMm7iODfpe1Gl0WeIqogGNp2rOZ8vynG9RSRtMC7A1o/I0CQQskrSHn78GPTb0eLODNn9iElEfHg5xolb9Cju/qUGDE2/psTWtjWkwSpxpySMlkCnc+AYm6eSunB5cxBkjXA1Q5AA5YP4j9ewHcYkbAcabY7DPPZCinGEb9xwm2F/5xscguYi6DGY/NeNH5QeJxSXIAYYFaY6AuQslXaRzc4CSH94mJGQ/dWO12B3OJnoprTYUTPZNrHICSC8eeKBtzzE+Y+OeA3hr1LcxbtfxkTY3o2eyFmVc0zgcXNeXlbNxHsQtEpdt+7GUHYAj/H1b/tOZE2LShFRQo1MrTbubggcvlbCq/oTerbXC0WJjJQOY5t7jTRXChAhvTiHNE=
