dist: bionic
language: go

go:
  - 1.13.x
  # - master

env:
  global:
    secure: "ACdUU1foPIsNHrVYmUybEYHAoruj/RcoFE1gAVDELg6Ab0V2vZsF1aroHvA4PZSfqd3y8/2Mh4ybSp2J7z7VPoLtwEsTyZoao6HigAIgVy53BXKrhDA3WAef/D6wWX/UHDPY/1Iqo8j7dCpX2HsHtwB22hNAyyJvsbbmnwmsKQ0rs6kHM40/naOCjG9Pakwn+TM5eRaGUJdXSM4H68lBg9CIq8cZnNjhL3h2//tnPB29DGRuKM1A8v9OtH2E1iaeQy+4nKOY/Z9Wh3uZ1n5lVO6fRgaiL9D3DgXZynmFkEsCLbHBOloPArMDq3xgM4p5ERvHzsbT0a8AwP53UNhtUubFg/BbbwzFUMwcVjVvv3avTM7jS/SCuZwEWx75agdj8EeZJIgbtKq+jKNxhV7/2FuG9tZfHZhLz/7ZkjteVBUBIXLQhjUuVXp4kZ4Tfzr1cUC/f1kixi6ZfAqoudi1udp+LQNQ07pH1pFEQyDvrv7fjrJjkI1qut5o5piWq8JeKOSwurjJDKoRUYFL+1upsRITjVt3NeskRk+XSxVYWMwaE3zfNJNnbfA6ZefXhwkUgoQk0MgGdxp/1bv6aAFjCGOaIRhVrKsb4XIx8SxSgxythBeYPEWWrQdtJqPy00YeWrcpnmYkQ0LHemYW4msXEcX1BHHHP9/1wjFszr+baHk="

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

go_import_path: github.com/Percona-Lab/pmm-api-tests

before_cache:
  - go clean -testcache

cache:
  directories:
    - /home/travis/.cache/go-build
    - /home/travis/gopath/pkg

install:
  # ensure that vendor/ is in sync with code and Gopkg.toml/lock
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep check
  # install reviewdog and golangci-lin
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s

before_script:
  - make init
  # static analyze
  - make ci-reviewdog

script:
  - make build

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: jl8m0thPSqXXGZqjh5ysqKz+SsAupsEcJdiaMvO4hemjJYqWvsXLjRX7DXNyery05/82LvBHuuop7uDkW/kRVRoX8QDv1clafXXaOe/llHQu3aYwPIkKM1vk+PFkK2A+yHK/pnLSuiA4/bT8qo8U0oVHIxoNiaBtbK1jx3theA/QDZZoUUwI/nt7AT8yld4uPCSl/pJlc2H01yJTw7mpWSNARBtIQkhjlHpT0NGvcvdIPk7MzcYaBNdbHBp1b8jLmTvY4ji4J/QxlUmtMFiaokcRoBjmcWq4x7cwqrNPLYc3fBADIk8ZZi/NS6O6Tl95OqEpqrLon0zgAEYrA0ahBwgJ1aW1t2D/Nl4Z3tZV4IfJkks59kjZvjIOABzYcxxrh/CiBU4XbM0Oqn4R7w2FuS1xi/SQLrTgEkVtchUDuYpNmTyczQdFu8/+edNX0WkZwe+F7qtlotPZZ9hlSdtsMwsWJ6PM+/Clp1Z9dSghHI5rRqwiByVz67TM22Jz6R8TRXK94qS0BC4x2WKJGbDvcnCWtV1Vjjv5arEx6jNUAeipsgqHYat3TQoLWDnbqRca2w6QkmJgSV3Utccbtv51dSvLOo7gbE7ijjUB+zGe/Q5JY9jD4pXnso7gClTTV/G4QOX/mkh9829W0V2J7Miv0Nt8mNI0r5USiInxpTqgdFY=
