dist: bionic
language: go
os: linux

go:
  - 1.15.x
  - tip

env:
  global:
    # REVIEWDOG_GITHUB_API_TOKEN
    secure: EaQ5dC5pg6donGFAROkzIgETFi5SV9GFaL1wCnL6Etj2NR/ggqdqjdJOkd9rtBAYUPRB968Arfun21yl1bknVB9lLz97zZuUSSfBBqXzm3npI3GunAkaJVCgZ8Q72w9WfQySp18+TdeDAA7HjlzinbVs9Lt9c1qIzbnOTYLH35ChdZuj1pztUx07SclCrQ55hw6lqQhG6GYhGFlTwUOl8zgJBBND4QjOJ8iZ0L3t2bqzpUKLtAB3JGxGku6OFyLkGJhA1Hr/+BkODsYeZeHWwBXJ5HceiduyU+Z/xcwBmaUSqzoaTVT0DfH6oP4n1VHj6wFJWSAc50P12I9Mi1JzKXUdBMlvIBmBZ9jt3PWqPcLpjCGOWklUuNDMDE94rmJ3RkC9uqQWRm+G8ivPQ3UjeswOT4xFDNBGjWppyc2TNOaVWxs/lDfF2Qt4ElgyjZHa0q3IE5sdz6KF+cDUbfoSak3bLkch9RQXATq+ywS/ztmlXnN/79RULXWRjITDFcf/UIbpEsJ19tac6lQ4/TYPXMdorZP4OMp7tDfmHC4C91rOqfq+eJOnQ3Q+2W4WdPcybF1SeFyzuTqDRAhJkviwlGkS4M3hD9ypAzThfiT88uF0Uu7lX2ZSQkj9OsfBZH0L5OmBdj12BmfjVQFiBRK5H6EKAymj09KO/8zeJz0CUq4=

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

go_import_path: github.com/Percona-Lab/pmm-api-tests

before_cache:
  - go clean -testcache

cache:
  directories:
    - /home/travis/.cache/go-build
    - /home/travis/gopath/pkg

install: skip

before_script:
  - make init
  # static analyze
  - make ci-reviewdog

script:
  - make build

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: gTKEC2zDy4rgO/4X681WlbET05gpNjVYLQgI7V1VXY1D9/1ZYI1KymY0VchIWDp+uc8YQX4eYSAdmzDi77kYpSCj4/dfGyDqzFSqJ9JFbqCbwQq82ng1+CD6SPcLKb+embX1cqsp1bnQoFY4jxNB9glFLY8izWAhoQvu6vTe0LUrFlF35AyZg+BgFZ7vxSWL5PL6yQmGwakuCCP800vn333ynjB3vWu8KtYz6E8euhEEd3lpcrC557IwRwUNbUGk5e9EvfB3/682+uQboz7Kj0aG2DriOzmb+sLd6im37vN77Ho3Oj0lVCUxcQCy5c0oiWKdTsr1wN7BRvA4HgHX5T1UUoVlJruKkl03I0m3IfWfCrF9k9iZEaVvweYzas1LbqEduFKXyEUSZ/oIc9zIzUqgO36uXAoD7k0KY4JKFjaRYNuGX4UgZj6Uw1hCpfIFCboP1kMl4E7ilganWJB+sISQAj9KO+vHWjNS/rkYxKHvq1a9qK4MrBkfvuZjgKpgmg1iAK220v7T/mvjGZ4PGywYAxNMFx5d7Yl7Y5hFaD4pS5DVxP3VVg3LyFW1K4euUfBRDGZbno46mQGQilx9dvzpm5TJKwQyUyF01L4ABV79JKCCM1CeIuUReE7hTOkxRB9SU8CrrErBzONcIN3NKLp7cOLQRyz7AcnCGQvZBPQ=
